### ISSUE TITLE
Формат файла для --filename

### ISSUE THREAD

**Issue by FreemanBel** [DavisDmitry/tg-session-keeper#5]
Сгенерировал сессию, используя `telethon.sessions import StringSession` - длинная шифрованная строка.
Поместил в файл, скормил через параметр `--filename`, но пишет:
`session-keeper: error: argument --filename: invalid typing.Optional[str] value: './file.session'`
Какого вида должен быть файл с сессией?

**Comment by DavisDmitry** [comment]
Используется собственный формат файлов. Скормить сессию, сгенерированную Telethon не получится. Просто запустите программу, файл с сессиями будет создан в директории, откуда произошёл запуск.

**Comment by FreemanBel** [comment]
Ясно, спасибо! Вопрос закрыт.
